services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/nginx/:/etc/nginx/
    environment:
      - INFLUX_DOMAIN=${INFLUX_DOMAIN:-influx.p6.test}
      - GRAFANA_HOST=${GRAFANA_HOST:-grafana.p6.test}
      - NODERED_HOST=${NODERED_HOST:-nodered.p6.test}
    depends_on:
      - influxdb
      - grafana
      - nodered
    
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_DB}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "33:33"
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUX_ORG=${INFLUXDB_ORG}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
      - ./data/grafana:/var/lib/grafana

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    user: "33:33"
    ports:
      - "1880:1880"
    volumes:
      - ./data/node-red:/data

  cloudflared:
    profiles: ['prod']
    build: ./dockerfiles/cloudflared/
    depends_on:
      - nginx
    restart: always
    volumes:
      - ./config/cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_ID=${TUNNEL_ID}
      - WILDCARD_DOMAIN=${WILDCARD_DOMAIN}