FROM python:3.11

# Create virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Set working directory
WORKDIR /app/

COPY cda/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt